version: 2
# https://circleci.com/developer/orbs/orb/circleci/aws-ecr
 aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install awscli
      - run: $(aws ecr get-login --no-include-email --region us-east-1)
      - run: docker build -t my-ecr-repo .
      - run: docker tag my-ecr-repo:latest 148774211651.dkr.ecr.us-east-1.amazonaws.com/mahira:latest
      - run: docker push 148774211651.dkr.ecr.us-east-1.amazonaws.com/mahira:latest
      
workflows:
  pushimage:
    jobs:
      - build
      #Envs: AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
      - aws-ecr/build-and-push-image:
          repo: mahira
            path: .
              requires:
                - build
